Vagrant.configure("2") do |config|

	config.vm.network "private_network", ip: "192.168.33.13"
	config.vm.synced_folder "../", "/vagrant"
 
 	config.vm.box = "ubuntu/trusty64"
 
	config.vm.provider "virtualbox" do |vb|
	end
	
	config.vm.provision "shell", 
	path: "./remove_containers_and_images.sh"

	config.vm.provision "docker" do |d|
		
		
		#`docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker rmi $(docker images -aq)`	
		d.build_image "/vagrant/",
		args: "-f /vagrant/deployment/gateway-service/Dockerfile -t gateway-service"
            
            d.build_image "/vagrant/",
            args: "-f /vagrant/deployment/java-parser-service/Dockerfile -t java-parser-service"
		
		d.pull_images "mongo"
		
		d.run "gateway-service",
		args: "-p 3002:3002 -d"
            
            d.run "java-parser-service",
            args: "-p 3006:3006 -d"
		
		d.run "mongo",
		args: "-p 27017:27017"
	end
end
