Vagrant.configure("2") do |config|

	config.vm.network "private_network", ip: "192.168.33.13"
	config.vm.synced_folder "../", "/vagrant"
 
 	config.vm.box = "ubuntu/trusty64"
 
	config.vm.provider "virtualbox" do |vb|
	end

	config.vm.provision "docker" do |d|
		
		d.build_image "/vagrant/",
		args: "-f /vagrant/deployment/gateway-service/Dockerfile -t gateway-service"
		
		d.build_image "/vagrant/deployment/gateway-service",
		args: "-t java-parser-service"
		
		d.run "gateway-service",
		args: "-p 3002:3002 -d"
		
		d.run "java-parser-service",
		args: "-p 3006:3006 -d"

	end
end
